Gessielsp/corporali

pages/pagAbdominais.jsx
status: mano, criei a pagina de abdominais do doutor.
=> create: pagAbdominais criada

pages/pagBodyTite.jsx
=> criacao: pagina bodytite

pages/index.jsx, styles/index.module.scss
foi criada a pagina do Doutor marcelo
=> pagProcedimentos

pages/pagAbdominais.jsx, pages/pagFaciais.jsx, pages/pagMamarios.jsx, pages/pagReparadores.jsx, styles/pagAbdominais.module.scss
status: pagina de abdominais finalizada.
=> finalizado: pagina de abdominais finalizada

components/header/Header.jsx, components/header/Header.module.scss
status: acabei de fazer o select do header, da parte que fala dos procedimentos.
=> create: criado select de procedimentos

pages/procedimentos-reparadores.jsx, styles/pagReparatorios.module.scss
status: pagina de procedimentos reparadores finalizada.
=> finalizado: pagina de procedimentos reparadores

components/header/Header.jsx, components/header/Header.module.scss, pages/marcelo-moreira.jsx, styles/pagDrMarcelo.module.scss
status: pagina do dr finalizada.
=> finalizado: pagina dr marcelo concluida

package-lock.json, package.json, pages/clinica.jsx, styles/pagClinica.module.scss
=> finalizado: pagina de clinica

package-lock.json, package.json, pages/index.jsx, styles/index.module.scss
=> pag Home finalizada

pages/marcelo-moreira.jsx, pages/procedimentos-abdominais.jsx, pages/procedimentos-faciais.jsx, pages/procedimentos-mamarios.jsx, pages/procedimentos-reparadores.jsx, styles/index.module.scss, styles/pagAbdominais.module.scss, styles/pagClinica.module.scss, styles/pagDrMarcelo.module.scss, styles/pagFaciais.module.scss, styles/pagMamarios.module.scss, styles/pagReparatorios.module.scss
mudanças de "imports" e criação de @media
=> criação de const e @medias

components/header/Header.jsx, components/header/Header.module.scss, pages/bodytite.jsx, pages/clinica.jsx, pages/index.jsx, pages/marcelo-moreira.jsx, pages/procedimentos-abdominais.jsx, pages/procedimentos-faciais.jsx, pages/procedimentos-mamarios.jsx, pages/procedimentos-reparadores.jsx, styles/index.module.scss, styles/pagAbdominais.module.scss, styles/pagBodytite.module.scss, styles/pagClinica.module.scss, styles/pagDrMarcelo.module.scss, styles/pagFaciais.module.scss, styles/pagMamarios.module.scss, styles/pagReparatorios.module.scss
status: acabei de fazer as interações de todos os links do projeto.
=> interacao: interacao dos links feita

package-lock.json, pages/bodytite.jsx
status: erro ainda acontece, nessa PR arrumei uns links que estavam com problemas
=> correcao: erro build persiste, arrumei os links

components/header/Header.jsx, components/header/Header.module.scss, package-lock.json, package.json, pages/index.jsx
=> ajustes: arrumando header

components/header/Header.module.scss
=> arrumando header quando for para uma pagina

components/header/Header.jsx, components/header/Header.module.scss, package-lock.json, pages/index.jsx, styles/index.module.scss
status: acabei de fazer a adaptacao do da pagina index
=> adaptacao: index totalmente adaptada, foi feita

components/footer/Footer.jsx, components/footer/Footer.module.scss, pages/marcelo-moreira.jsx, styles/pagDrMarcelo.module.scss
status: adaptação da pagina do dr marcelo feita.
=> finalizado: adaptação da pagina do dr marcelo feita

components/footer/Footer.module.scss, components/header/Header.jsx, components/header/Header.module.scss, pages/marcelo-moreira.jsx, styles/pagDrMarcelo.module.scss
status: acabei de terminar 100% a adaptacao da pagina dele
=> adaptacao: pagina do marcelo 100 por cento adaptada

pages/clinica.jsx, styles/pagClinica.module.scss
status: add, ainda nao terminei
=> add estilizacao da pagina clinica

components/footer/Footer.jsx, components/header/Header.jsx, components/linhaHorizontalLonga/LinhaHorizontalLonga.jsx, package-lock.json, package.json, pages/_app.js, pages/bodytite.jsx, pages/clinica.jsx, pages/index.jsx, pages/marcelo-moreira.jsx, pages/procedimentos-abdominais.jsx, pages/procedimentos-faciais.jsx, pages/procedimentos-mamarios.jsx, pages/procedimentos-reparadores.jsx
status: corrigindo o erro que estava atrapalhando o build.
=> fix: resolvendo erro doido

pages/clinica.jsx, styles/pagClinica.module.scss
status: pagina 100 por cento adaptada.
=> adaptacao: cem por cento adaptado

package-lock.json, pages/bodytite.jsx, styles/pagBodytite.module.scss
status: pagina do bodytite 100% adaptada.
=> adaptacao: pagina do bodytite totalmente adaptada

pages/index.jsx, styles/index.module.scss
status: link de procedimentos add.
=> create: link de procedimentos feito

components/footer/Footer.module.scss, pages/procedimentos-reparadores.jsx, styles/pagReparatorios.module.scss
status: arrumando erro da pagina de reparadores
=> fix: resolvido erro na pagina de reparadores

pages/procedimentos-abdominais.jsx, pages/procedimentos-faciais.jsx, pages/procedimentos-mamarios.jsx, pages/procedimentos-reparadores.jsx, pages/video-abdominal.jsx, pages/video-faciais.jsx, pages/video-mamarios.jsx, pages/video-reparadores.jsx, styles/videos.module.scss
status: pagina de videos feita.
=> pagina de videos feita e adaptada

pages/testeFacial.jsx, styles/procedimentos.module.scss
status: a pagina de procedimentos que estou testando, foi finalizada.
=> finalizado: finalizei a pagina de teste facial

pages/video-abdominal.jsx, pages/video-faciais.jsx, pages/video-mamarios.jsx, pages/video-reparadores.jsx, styles/videos.module.scss
status: paginas de videos totalmente adaptadas.
=> adaptacao: das paginas de videos feita

pages/procedimentos-faciais.jsx, pages/procedimentos-mamarios.jsx, pages/procedimentos-reparadores.jsx, pages/video-abdominal.jsx, pages/video-faciais.jsx, pages/video-mamarios.jsx, pages/video-reparadores.jsx, styles/pagClinica.module.scss
status: corrigindo ultimos erros.
=> fix: correcao de erros

.env, package-lock.json, package.json, pages/api/enviarEmail.js, pages/index.jsx, utils/nodeMailer.js
status: servico de email funcionando.
=> fix: resolvido erro do email
